"""
Convert UAVDT-2024 dataset to YOLO format.
Skips van (class 3) and score=0 annotations.

Usage:
    python3 uavdt_to_yolo.py \
        --dataset /path/to/uavdt-2024 \
        --output  /path/to/uavdt_yolo \
        --split   train \
        --sequences M0101 M0201 ...   # optional, omit to use all

Output structure:
    uavdt_yolo/
        images/train/
        images/val/
        labels/train/
        labels/val/
        uavdt.yaml
"""

import argparse
import shutil
import os
from pathlib import Path
from collections import defaultdict

# UAVDT class mapping (skip van=3)
UAVDT_TO_YOLO = {
    0: 0,  # car   -> 0
    1: 1,  # truck -> 1
    2: 2,  # bus   -> 2
    # 3 = van -> skip
}

CLASS_NAMES = ['car', 'truck', 'bus']


def convert_box_to_yolo(x, y, w, h, img_w, img_h):
    cx = (x + w / 2) / img_w
    cy = (y + h / 2) / img_h
    nw = w / img_w
    nh = h / img_h
    cx = max(0.0, min(1.0, cx))
    cy = max(0.0, min(1.0, cy))
    nw = max(0.0, min(1.0, nw))
    nh = max(0.0, min(1.0, nh))
    return cx, cy, nw, nh


def get_image_size(path):
    import cv2
    img = cv2.imread(str(path))
    if img is None:
        return None, None
    h, w = img.shape[:2]
    return w, h


def write_yaml(output_path):
    yaml_content = f"""# UAVDT dataset for YOLOv8 finetuning
# Generated by uavdt_to_yolo.py

path: {output_path.resolve()}
train: images/train
val:   images/val

nc: {len(CLASS_NAMES)}
names: {CLASS_NAMES}
"""
    yaml_path = output_path / "uavdt.yaml"
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    print(f"[Info] YAML written to: {yaml_path}")


def convert(dataset_path, output_path, split, sequences):
    img_out = output_path / "images" / split
    lbl_out = output_path / "labels" / split
    img_out.mkdir(parents=True, exist_ok=True)
    lbl_out.mkdir(parents=True, exist_ok=True)

    stats = {"frames": 0, "objects": 0, "skipped": 0, "van_skipped": 0}

    for seq in sequences:
        seq_path = dataset_path / seq
        ann_dir  = seq_path / "annotations"
        img_dir  = seq_path / "images"

        if not ann_dir.exists() or not img_dir.exists():
            print(f"[Skip] Missing data for sequence: {seq}")
            continue

        ann_files = sorted(ann_dir.glob("*.txt"))
        print(f"[{split}] {seq} → {len(ann_files)} frames")

        for ann_file in ann_files:
            stem     = ann_file.stem  # e.g. img000001
            img_path = img_dir / f"{stem}.jpg"

            if not img_path.exists():
                stats["skipped"] += 1
                continue

            img_w, img_h = get_image_size(img_path)
            if img_w is None:
                stats["skipped"] += 1
                continue

            label_lines = []
            with open(ann_file, 'r') as f:
                for line in f:
                    parts = line.strip().split(',')
                    if len(parts) < 6:
                        continue
                    x, y, w, h = int(parts[0]), int(parts[1]), int(parts[2]), int(parts[3])
                    score    = int(parts[4])
                    cls_id   = int(parts[5])

                    if score == 0:
                        continue
                    if cls_id == 3:  # van
                        stats["van_skipped"] += 1
                        continue
                    if cls_id not in UAVDT_TO_YOLO:
                        continue
                    if w <= 0 or h <= 0:
                        continue

                    yolo_cls = UAVDT_TO_YOLO[cls_id]
                    cx, cy, nw, nh = convert_box_to_yolo(x, y, w, h, img_w, img_h)
                    label_lines.append(f"{yolo_cls} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")

            out_stem = f"{seq}_{stem}"
            shutil.copy2(img_path, img_out / f"{out_stem}.jpg")
            with open(lbl_out / f"{out_stem}.txt", 'w') as f:
                f.write("\n".join(label_lines))

            stats["frames"]  += 1
            stats["objects"] += len(label_lines)

    return stats


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset",   required=True, help="Path to uavdt-2024 root")
    parser.add_argument("--output",    required=True, help="Output path for YOLO dataset")
    parser.add_argument("--split",     required=True, choices=["train", "val"], help="Split name")
    parser.add_argument("--sequences", nargs="+", default=None, help="Sequence names (omit for all)")
    args = parser.parse_args()

    dataset_path = Path(args.dataset)
    output_path  = Path(args.output)

    # Auto-detect sequences if not specified
    if args.sequences:
        sequences = args.sequences
    else:
        sequences = sorted([
            d.name for d in dataset_path.iterdir()
            if d.is_dir() and d.name.startswith('M')
        ])

    print(f"[Info] Dataset: {dataset_path}")
    print(f"[Info] Output:  {output_path}")
    print(f"[Info] Split:   {args.split}")
    print(f"[Info] Sequences: {len(sequences)}")

    stats = convert(dataset_path, output_path, args.split, sequences)
    write_yaml(output_path)

    print(f"\n===== CONVERSION COMPLETE ({args.split}) =====")
    print(f"Frames:       {stats['frames']}")
    print(f"Objects:      {stats['objects']}")
    print(f"Van skipped:  {stats['van_skipped']}")
    print(f"Skipped:      {stats['skipped']}")


if __name__ == "__main__":
    main()