"""
Convert VisDrone-VID and VisDrone-DET datasets to YOLO format.
Maps VisDrone classes to COCO class IDs (consistent with eval_visdrone.py).

VID usage (run twice):
    python3 visdrone_to_yolo.py \
        --dataset /path/to/VisDrone2019-VID-train \
        --output  /path/to/visdrone_yolo \
        --split   train

    python3 visdrone_to_yolo.py \
        --dataset /path/to/VisDrone2019-VID-val \
        --output  /path/to/visdrone_yolo \
        --split   val

DET usage (run twice, same output folder):
    python3 visdrone_to_yolo.py \
        --dataset /path/to/VisDrone2019-DET-train \
        --output  /path/to/visdrone_yolo \
        --split   train

    python3 visdrone_to_yolo.py \
        --dataset /path/to/VisDrone2019-DET-val \
        --output  /path/to/visdrone_yolo \
        --split   val

Output structure:
    visdrone_yolo/
        images/
            train/   ← VID frames + DET images
            val/     ← VID frames + DET images
        labels/
            train/   ← YOLO labels for train
            val/     ← YOLO labels for val
        visdrone.yaml
"""

import argparse
import os
import shutil
from pathlib import Path
from collections import defaultdict
import cv2

# ── VisDrone -> COCO class mapping (same as eval_visdrone.py) ──
VISDRONE_TO_COCO = {
    1: 0,   # pedestrian -> person
    2: 0,   # people -> person
    4: 1,   # car -> car
    5: 1,   # van -> car
}

COCO_NAMES = {
    0: "person",
    1: "car",
}


def load_visdrone_annotations(txt_path):
    """
    Returns: dict {frame_id: [(coco_class, x, y, w, h), ...]}
    VisDrone VID format: frame_id,target_id,x,y,w,h,score,class,truncation,occlusion
    """
    frame_gt = defaultdict(list)
    with open(txt_path, 'r') as f:
        for line in f:
            parts = line.strip().split(',')
            if len(parts) < 8:
                continue
            frame_id  = int(parts[0])
            x, y, w, h = int(parts[2]), int(parts[3]), int(parts[4]), int(parts[5])
            score     = int(parts[6])
            vis_class = int(parts[7])

            if score == 0:
                continue
            if vis_class not in VISDRONE_TO_COCO:
                continue
            if w <= 0 or h <= 0:
                continue

            frame_gt[frame_id].append((VISDRONE_TO_COCO[vis_class], x, y, w, h))
    return frame_gt


def load_det_annotations(txt_path):
    """
    Returns: list of (coco_class, x, y, w, h)
    VisDrone DET format: x,y,w,h,score,class,truncation,occlusion
    """
    boxes = []
    with open(txt_path, 'r') as f:
        for line in f:
            parts = line.strip().split(',')
            if len(parts) < 8:
                continue
            x, y, w, h = int(parts[0]), int(parts[1]), int(parts[2]), int(parts[3])
            score     = int(parts[4])
            vis_class = int(parts[5])

            if score == 0:
                continue
            if vis_class not in VISDRONE_TO_COCO:
                continue
            if w <= 0 or h <= 0:
                continue

            boxes.append((VISDRONE_TO_COCO[vis_class], x, y, w, h))
    return boxes


def convert_box_to_yolo(x, y, w, h, img_w, img_h):
    """Convert pixel (x,y,w,h) top-left to normalized YOLO (cx,cy,w,h)."""
    cx = (x + w / 2) / img_w
    cy = (y + h / 2) / img_h
    nw = w / img_w
    nh = h / img_h
    cx = max(0.0, min(1.0, cx))
    cy = max(0.0, min(1.0, cy))
    nw = max(0.0, min(1.0, nw))
    nh = max(0.0, min(1.0, nh))
    return cx, cy, nw, nh


def get_image_size(path):
    img = cv2.imread(str(path))
    if img is None:
        return None, None
    h, w = img.shape[:2]
    return w, h


def write_yaml(output_path):
    class_ids   = sorted(COCO_NAMES.keys())
    class_names = [COCO_NAMES[i] for i in class_ids]
    yaml_content = f"""# VisDrone -> COCO mapped dataset for YOLOv8 finetuning
# Generated by visdrone_to_yolo.py

path: {output_path.resolve()}
train: images/train
val:   images/val

nc: {len(class_names)}
names: {class_names}

# Class ID mapping from COCO -> contiguous
# 0=person, 1=bicycle, 2=car, 3=motorcycle, 4=bus, 5=truck
"""
    yaml_path = output_path / "visdrone.yaml"
    with open(yaml_path, 'w') as f:
        f.write(yaml_content)
    print(f"[Info] YAML written to: {yaml_path}")


def convert_vid(dataset_path, output_path, split):
    """Handle VisDrone-VID format (sequences/ + annotations/)."""
    seq_dir = dataset_path / "sequences"
    ann_dir = dataset_path / "annotations"

    (output_path / "images" / split).mkdir(parents=True, exist_ok=True)
    (output_path / "labels" / split).mkdir(parents=True, exist_ok=True)

    sequences = []
    for seq in sorted(os.listdir(seq_dir)):
        if seq.startswith("."):
            continue
        ann_file = ann_dir / f"{seq}.txt"
        if not ann_file.exists():
            print(f"[Skip] No annotation for: {seq}")
            continue
        sequences.append(seq)

    print(f"[Info] VID format detected — {len(sequences)} sequences → '{split}' split")
    stats = {"frames": 0, "objects": 0, "skipped": 0}

    for seq in sequences:
        ann_file = ann_dir / f"{seq}.txt"
        frames   = sorted((seq_dir / seq).glob("*.jpg"))
        frame_gt = load_visdrone_annotations(ann_file)

        for frame_path in frames:
            frame_id = int(frame_path.stem)
            gt_boxes = frame_gt.get(frame_id, [])

            img_w, img_h = get_image_size(frame_path)
            if img_w is None:
                stats["skipped"] += 1
                continue

            label_lines = []
            for cls_id, x, y, w, h in gt_boxes:
                cx, cy, nw, nh = convert_box_to_yolo(x, y, w, h, img_w, img_h)
                label_lines.append(f"{cls_id} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")

            stem    = f"{seq}_{frame_path.stem}"
            img_dst = output_path / "images" / split / f"{stem}.jpg"
            lbl_dst = output_path / "labels" / split / f"{stem}.txt"

            shutil.copy2(frame_path, img_dst)
            with open(lbl_dst, 'w') as f:
                f.write("\n".join(label_lines))

            stats["frames"]  += 1
            stats["objects"] += len(gt_boxes)

        print(f"[{split}] {seq} → {len(frames)} frames")

    return stats


def convert_det(dataset_path, output_path, split):
    """Handle VisDrone-DET format (images/ + annotations/)."""
    img_dir = dataset_path / "images"
    ann_dir = dataset_path / "annotations"

    (output_path / "images" / split).mkdir(parents=True, exist_ok=True)
    (output_path / "labels" / split).mkdir(parents=True, exist_ok=True)

    images = sorted(img_dir.glob("*.jpg"))
    print(f"[Info] DET format detected — {len(images)} images → '{split}' split")
    stats = {"frames": 0, "objects": 0, "skipped": 0}

    for img_path in images:
        ann_file = ann_dir / f"{img_path.stem}.txt"
        if not ann_file.exists():
            stats["skipped"] += 1
            continue

        img_w, img_h = get_image_size(img_path)
        if img_w is None:
            stats["skipped"] += 1
            continue

        gt_boxes = load_det_annotations(ann_file)

        label_lines = []
        for cls_id, x, y, w, h in gt_boxes:
            cx, cy, nw, nh = convert_box_to_yolo(x, y, w, h, img_w, img_h)
            label_lines.append(f"{cls_id} {cx:.6f} {cy:.6f} {nw:.6f} {nh:.6f}")

        stem    = f"det_{img_path.stem}"   # prefix to avoid name collisions with VID
        img_dst = output_path / "images" / split / f"{stem}.jpg"
        lbl_dst = output_path / "labels" / split / f"{stem}.txt"

        shutil.copy2(img_path, img_dst)
        with open(lbl_dst, 'w') as f:
            f.write("\n".join(label_lines))

        stats["frames"]  += 1
        stats["objects"] += len(gt_boxes)

    return stats


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--dataset", required=True, help="Path to VisDrone dataset split root")
    parser.add_argument("--output",  required=True, help="Output path for YOLO-format dataset")
    parser.add_argument("--split",   required=True, choices=["train", "val"], help="Which split")
    args = parser.parse_args()

    dataset_path = Path(args.dataset)
    output_path  = Path(args.output)
    split        = args.split

    # Auto-detect VID vs DET format
    if (dataset_path / "sequences").exists():
        stats = convert_vid(dataset_path, output_path, split)
    elif (dataset_path / "images").exists():
        stats = convert_det(dataset_path, output_path, split)
    else:
        print(f"[Error] Could not detect VID or DET format in: {dataset_path}")
        print("Expected either a 'sequences/' folder (VID) or 'images/' folder (DET).")
        return

    write_yaml(output_path)

    print(f"\n===== CONVERSION COMPLETE ({split}) =====")
    print(f"Frames:   {stats['frames']}")
    print(f"Objects:  {stats['objects']}")
    print(f"Skipped:  {stats['skipped']}")


if __name__ == "__main__":
    main()